changelog:
  categories:
    - title: 新功能
      labels:
        - enhancement
        - feature
    - title: 问题修复
      labels:
        - bug
        - fix
    - title: 文档
      labels:
        - documentation
    - title: 依赖更新
      labels:
        - dependencies
    - title: 其他改动
      labels:
        - "*"

  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
